let E=JSON.parse(localStorage.getItem("cud_att_demo")||"[]"),current="";
function save(){localStorage.setItem("cud_att_demo",JSON.stringify(E));stats()}function page(id){document.querySelectorAll("main section").forEach(x=>x.classList.add("hide"));document.getElementById(id).classList.remove("hide");stats()}
function stats(){ne.textContent=E.length;mq.textContent=E.reduce((s,e)=>s+e.qr.length,0);mm.textContent=E.reduce((s,e)=>s+(+e.manual||0),0);mt.textContent=E.reduce((s,e)=>s+e.qr.length+(+e.manual||0),0)}
function code(){let y=new Date().getFullYear(),a=E.map(e=>+e.code.split("-").pop());return `CUD-EVT-${y}-${String(Math.max(0,...a)+1).padStart(4,"0")}`}function ev(c){return E.find(e=>e.code==c)}
eventForm.onsubmit=x=>{x.preventDefault();let d=Object.fromEntries(new FormData(eventForm));d.code=code();d.qr=[];d.manual=0;d.photos=[];E.push(d);save();current=d.code;createdName.textContent=d.name;createdCode.textContent=d.code;page("created");qr.innerHTML="";new QRCode(qr,{text:location.href.split("?")[0]+"?attendance="+encodeURIComponent(d.code),width:210,height:210});eventForm.reset()}
function drawEvents(){rows.innerHTML=E.map(e=>`<tr><td>${e.code}</td><td>${e.name}</td><td>${e.qr.length}</td><td>${e.manual||0}</td><td><b>${e.qr.length+(+e.manual||0)}</b></td><td><button onclick="participant('${e.code}')">QR Form</button><button class="primary" onclick="post('${e.code}')">Post Event</button></td></tr>`).join("")||'<tr><td colspan="6">No events yet.</td></tr>'}
function participant(c){let e=ev(c);if(!e)return;current=c;pTitle.textContent=e.name;pCode.textContent=e.code;pmsg.textContent="";page("participant")}ptype.onchange=()=>{let st=ptype.value=="CUD Student";sidWrap.style.display=st?"flex":"none";progWrap.style.display=st?"flex":"none"};ptype.onchange()
pForm.onsubmit=x=>{x.preventDefault();let e=ev(current),key=(email.value||sid.value||phone.value||((first.value+" "+last.value).toLowerCase()));if(e.qr.some(a=>a.key==key)){pmsg.textContent="Attendance already recorded.";return}e.qr.push({key,type:ptype.value,first:first.value,last:last.value,email:email.value,phone:phone.value,student_id:sid.value,program:program.value,time:new Date().toISOString()});save();pmsg.textContent="✓ Attendance recorded successfully.";pForm.reset();ptype.onchange()}
function post(c){let e=ev(c);current=c;postName.textContent=e.name;postCode.textContent=e.code;qrCount.textContent=e.qr.length;manualNow.textContent=e.manual||0;totalNow.textContent=e.qr.length+(+e.manual||0);manualCount.value=e.manual||0;remarks.value=e.remarks||"";postmsg.textContent="";page("post")}
postForm.onsubmit=x=>{x.preventDefault();let e=ev(current);e.manual=+manualCount.value||0;e.photos=[...photos.files].map(f=>f.name);e.remarks=remarks.value;save();manualNow.textContent=e.manual;totalNow.textContent=e.qr.length+e.manual;postmsg.textContent="✓ Post-event information saved. Total Attendance = QR Attendance + Manual Attendance.";drawEvents()}
stats();let q=new URLSearchParams(location.search).get("attendance");if(q&&ev(q))participant(q);